# BorderTeleport Plugin Configuration

# MySQL settings (ensure these keys exist in your config if you use MySQL)
mysql:
  host: localhost
  port: 3306
  database: minecraft_transfer
  username: root
  password: yourpassword
  useSSL: false
  allowPublicKeyRetrieval: true

# The name of the current server (must match what is used in BungeeCord)
server-name: "southwest"

# Define the region boundaries for each server.
regions:
  # The northwest region represents the top-left quadrant of the world.
  # Players in this area are on the "Server1" instance.
  northwest:
    server-name: "Server1"  # The name of the server that manages this region, must match BungeeCord config
    min-x: -8192            # Western boundary of the northwest region
    max-x: 0                # Eastern boundary (center of the world)
    min-z: -8192            # Northern boundary of the northwest region
    max-z: 0                # Southern boundary (center of the world)

  # The northeast region represents the top-right quadrant of the world.
  # Players in this area are on the "Server2" instance.
  northeast:
    server-name: "Server2"
    min-x: 0
    max-x: 8192
    min-z: -8192
    max-z: 0

  # The southwest region represents the bottom-left quadrant of the world.
  # Players in this area are on the "Server3" instance.
  southwest:
    server-name: "Server3"
    min-x: -8192
    max-x: 0
    min-z: 0
    max-z: 8192

  # The southeast region represents the bottom-right quadrant of the world.
  # Players in this area are on the "Server4" instance.
  southeast:
    server-name: "Server4"
    min-x: 0
    max-x: 8192
    min-z: 0
    max-z: 8192

# Enable or disable messages when a player tries to teleport to an offline server
notify-server-offline: true

# Message to send when a server is offline (if notify-server-offline is enabled)
server-offline-message: "&cThe path ahead is closed. The server is offline."

# Message settings for offline server notifications
show-offline-message: true
offline-message: "The server you are trying to reach is offline!"

teleport:
  # Offset applied when transferring players (in blocks)
  offset: 20

  # Base timeout for pending teleports (in seconds)
  request-timeout: 30

  # Additional time given if the player is attempting to connect (in seconds)
  grace-period: 15

  # Number of times to retry a failed teleport
  max-retries: 3

  # Delay between retry attempts (in seconds)
  retry-delay: 2
