# BorderTeleport Plugin Configuration

# The name of the current server (must match what is used in BungeeCord)
server-name: "southwest"

# Define the region boundaries for each server.
# Each region should have its corresponding BungeeCord server name.
regions:
  # The northwest region represents the top-left quadrant of the world.
  # Players in this area are on the "Server1" instance.
  northwest:
    server-name: "Server1"  # The name of the server that manages this region.
    min-x: -8192  # Western boundary of the northwest region (leftmost edge).
    max-x: 0  # Eastern boundary of the northwest region (center of the world).
    min-z: -8192  # Northern boundary of the northwest region (topmost edge).
    max-z: 0  # Southern boundary of the northwest region (middle of the world).

  # The northeast region represents the top-right quadrant of the world.
  # Players in this area are on the "Server2" instance.
  northeast:
    server-name: "Server2"  # The name of the server that manages this region.
    min-x: 0  # Western boundary of the northeast region (center of the world).
    max-x: 8192  # Eastern boundary of the northeast region (rightmost edge).
    min-z: -8192  # Northern boundary of the northeast region (topmost edge).
    max-z: 0  # Southern boundary of the northeast region (middle of the world).

  # The southwest region represents the bottom-left quadrant of the world.
  # Players in this area are on the "Server3" instance.
  southwest:
    server-name: "Server3"  # The name of the server that manages this region.
    min-x: -8192  # Western boundary of the southwest region (leftmost edge).
    max-x: 0  # Eastern boundary of the southwest region (center of the world).
    min-z: 0  # Northern boundary of the southwest region (middle of the world).
    max-z: 8192  # Southern boundary of the southwest region (bottommost edge).

  # The southeast region represents the bottom-right quadrant of the world.
  # Players in this area are on the "Server4" instance.
  southeast:
    server-name: "Server4"  # The name of the server that manages this region.
    min-x: 0  # Western boundary of the southeast region (center of the world).
    max-x: 8192  # Eastern boundary of the southeast region (rightmost edge).
    min-z: 0  # Northern boundary of the southeast region (middle of the world).
    max-z: 8192  # Southern boundary of the southeast region (bottommost edge).

# Enable or disable messages when a player tries to teleport to an offline server
notify-server-offline: true

# Message to send when a server is offline (if notify-server-offline is enabled)
server-offline-message: "&cThe path ahead is closed. The server is offline."

# Teleport cooldown (in milliseconds) to prevent multiple rapid crossings
teleport-cooldown-ms: 3000

# Message displayed when a player tries to cross into an offline server.
# Set "show-offline-message" to false to disable the message.
show-offline-message: true
offline-message: "The server you are trying to reach is offline!"
