name: BorderTeleport
version: 1.0
main: com.yourplugin.BorderTeleport
api-version: 1.20
description: A plugin that teleports players when they reach the world border.
author: YourName
commands:
  border:
    description: Reload the BorderTeleport configuration.
    usage: /border reload
    permission: borderteleport.reload
permissions:
  borderteleport.reload:
    description: Allows reloading the BorderTeleport configuration.
    default: op