name: BorderTeleport
main: studio.magemonkey.borderteleport.BorderTeleport
version: 1.0
api-version: 1.16
commands:
  borderteleport:
    description: "Manage BorderTeleport commands, including reload."
    usage: /<command> reload
    permission: borderteleport.reload
    permission-message: "You do not have permission to use this command."
